/**
 * Re-vendors the SRCL components the playground uses.
 *
 * SRCL (MIT, Internet Development Studio Company) has no npm package, so its sources live in
 * `vendor/srcl/`. Everything here is generated: run `node playground/scripts/vendor-srcl.mjs` to
 * re-sync, rather than editing the vendored files.
 *
 * Sources are copied verbatim apart from a provenance header and `@ts-nocheck` — SRCL's own
 * tsconfig is looser than this repo's, and vendored code should not have to satisfy our rules.
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const REPO = "internet-development/www-sacred";
const WANTED = ["Badge", "BlockLoader", "Button", "Card", "Divider", "Input", "Table", "TableColumn", "TableRow"];

const root = fileURLToPath(new URL("../vendor/srcl/", import.meta.url));

const sha = await (async () => {
  const res = await fetch(`https://api.github.com/repos/${REPO}/commits/main`);
  if (!res.ok) throw new Error(`Cannot resolve ${REPO}@main: ${res.status}`);
  return (await res.json()).sha;
})();

const raw = (path) => `https://raw.githubusercontent.com/${REPO}/${sha}/${path}`;

async function fetchText(path, { optional = false } = {}) {
  const res = await fetch(raw(path));
  if (!res.ok) {
    if (optional) return undefined;
    throw new Error(`${path}: ${res.status}`);
  }
  return res.text();
}

const header = (path) =>
  `// Vendored from https://github.com/${REPO}/blob/${sha}/${path}\n` +
  `// MIT © Internet Development Studio Company. Generated by playground/scripts/vendor-srcl.mjs — do not edit.\n` +
  `// @ts-nocheck\n`;

await rm(root, { recursive: true, force: true });
await mkdir(new URL("components/", `file://${root}`), { recursive: true });
await mkdir(new URL("common/", `file://${root}`), { recursive: true });

const queue = [...WANTED];
const done = new Set();

while (queue.length) {
  const name = queue.shift();
  if (done.has(name)) continue;
  done.add(name);

  const path = `components/${name}.tsx`;
  const source = await fetchText(path);
  await writeFile(new URL(`components/${name}.tsx`, `file://${root}`), header(path) + source);

  const css = await fetchText(`components/${name}.module.css`, { optional: true });
  if (css) await writeFile(new URL(`components/${name}.module.css`, `file://${root}`), css);

  for (const [, dep] of source.matchAll(/from '@components\/([A-Za-z]+)'/g)) queue.push(dep);
}

const utilities = "common/utilities.ts";
await writeFile(new URL("common/utilities.ts", `file://${root}`), header(utilities) + (await fetchText(utilities)));
await writeFile(new URL("global.css", `file://${root}`), await fetchText("global.css"));
await writeFile(new URL("LICENSE.md", `file://${root}`), await fetchText("LICENSE.md"));

const files = (await readdir(new URL("components/", `file://${root}`))).filter((f) => f.endsWith(".tsx"));
console.log(
  `vendored ${files.length} components from ${REPO}@${sha.slice(0, 7)}: ${files.map((f) => f.replace(".tsx", "")).join(", ")}`,
);
