name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          node-version: "24"

      - name: Install dependencies
        run: pnpm install

      - name: Lint and format
        run: pnpm exec biome check .

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test:unit
